development: &base
  adapter: mysql2
  encoding: utf8
  reconnect: false
  port: 3306
  pool: 5
  database: <%= Rails.application.secrets.db_name %>
  host: <%= Rails.application.secrets.db_host %>
  username: <%= Rails.application.secrets.db_username %>
  password: <%= Rails.application.secrets.db_password %>

test:
  <<: *base
